name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: build/production/Dockerfile
          tags: ${{ secrets.DOCKER_USER }}/app:latest
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTIP }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
                echo "Logging into DockerHub"
                docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
                echo "Removing currently running Docker containers"
                docker ps -aq | xargs docker stop | xargs docker rm
                echo "Deleting images"
                docker image rmi $(docker images -q)
                echo "Starting new container"
                docker run -d -p 80:8080 ${{ secrets.DOCKER_USER }}/app:latest
